### ISSUE TITLE
API endpoint filter 

### ISSUE THREAD

**Issue by dametts** [leandrocfe/filament-tables-json-data-source#1]
hi, 
How would you pass parameters (from the filament filters) to the API endpoint URL/body?

thanks for your implementation btw :)

**Comment by leandrocfe** [comment]
> hi, 
> How would you pass parameters (from the filament filters) to the API endpoint URL/body?
> 
> thanks for your implementation btw :)
> 
> 
> 
> 

Hi! I haven't tried it before. I'll check it and I let you know 👍

**Comment by dametts** [comment]
Maybe i figured it out, 
![image](https://user-images.githubusercontent.com/19249735/213160432-e92fb470-753f-47c0-b11a-055caed9fd4a.png)

![image](https://user-images.githubusercontent.com/19249735/213160646-72f9356b-c2a0-4d69-8a7b-bcaabfa9351b.png)

Thanks,

**Comment by invaders-xx** [comment]
@dametts, how did you make it working? I implemented like the 2 previous screenshots but I get :
https://flareapp.io/share/V7j2kLk7
Many thanks for your help
